add separate arm build test

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -16,16 +16,68 @@ on:
 
 jobs:
   snap:
-    strategy:
-      matrix:
-        architecture: [amd64, arm64]
-    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@feat/add-arm-builds
+    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
     secrets:
       store-login: ${{ secrets.STORE_LOGIN }}
     with:
       branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
       snap-name: ros2-teleop
-      architecture: ${{ matrix.architecture }}
+      publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+      test-script: |
+        #!/bin/bash
+
+        check_existence() {
+          local topic_or_node="${1}"
+          local name="${2}"
+          local timeout="${3}"
+          local start_time=$(date +%s)
+
+          while true; do
+            ros2 "${topic_or_node}" list | grep -q "${name}"
+            if [ $? -eq 0 ]; then
+              echo "${name} is running."
+              return 0
+            fi
+
+            local current_time=$(date +%s)
+            local elapsed_time=$((current_time - start_time))
+
+            if [ $elapsed_time -ge $timeout ]; then
+              echo "Error $name is not running."
+              exit 1
+            fi
+            sleep 1
+          done
+        }
+
+        ## Connect interfaces
+        sudo snap connect ros2-teleop:hardware-observe
+        sudo snap connect ros2-teleop:joystick
+        sudo snap restart ros2-teleop
+
+        ## set a joystick configuration
+        sudo snap set ros2-teleop joy-config="ps3"
+
+        ## Install ROS 2 cli
+        sudo snap install ros2-cli --channel=humble/beta
+
+        sudo snap start ros2-teleop.joy
+
+        ## check that services are available
+        check_existence topic joy_vel 30
+        check_existence topic joy 30
+        check_existence node joy_node 30
+        check_existence node teleop_twist_joy_node 30
+
+        sudo snap stop ros2-teleop.joy
+
+  snap-arm:
+    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap-arm.yaml@feat/add-arm-builds
+    secrets:
+      store-login: ${{ secrets.STORE_LOGIN }}
+    with:
+      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
+      snap-name: ros2-teleop
       publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
       test-script: |
         #!/bin/bash
